Feat/6
kugods-HabitTama/dahae-server pull request #12
Opened 2022-11-26 15:09 UTC by yunz0926

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [X] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 요구사항 바탕으로 자체 회원가입 & 로그인 구현하였습니다.
- 자체 회원가입 시 프론트 쪽에서 중복 이메일 체크하는 api가 필요할 것 같아 추가하였습니다.

## Related issue
- #6 

## Additional context
- JWT 토큰 관련 환경 변수 추가사항은 슬랙으로 공유 드리겠습니다.

## Checklist
- refresh token 저장 방법에 대해 논의가 필요해보입니다. DB에서 User 데이터에 추가하여 저장하거나, Token 테이블을 새로 생성하는 두 가지 방법을 생각중인데 의견 주시면 감사하겠습니당

2022-11-27 04:44 UTC, worjs requested changes
와우 역시 잘하시네요... 고생하셨습니다! 
전체적인 로직은 제가 봤을때는 크게 문제가 없어보이고, 코멘트 드린 부분은 제가 공유를 못드린 팀 컨벤션(?)이나 사소한 부분들이어서, 읽어보시고 반영 가능한 부분들은 반영해주시면 될 것 같습니다. 따로 납득이 안되는 부분은 언제든지 코멘트 달아주세요!

추가적으로,
1. refresh_token은 user table에 column 하나 추가해서 저장하는게 깔끔해보이는데, 별도의 table로 구성했을때 장단점에 대해서 생각해두신 부분이 있으신가요?
2. controller에서 swagger 명세가 덜 세팅된 부분이 있습니다! test api 참고하셔서 더 작성해주시면 되겠습니다. 요청객체, 응답객체, param, query 등의 정보는 포함되어야 한다고 생각합니다. 주소는 요기니까 확인해 보시면 되겠습니다~ http://localhost:3000/docs/#/

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.service.ts
> +    if (!user) throw new Error('Email does not exist');
단순히 Error객체를 던져주는 것 보다는 nest에서 제공하는 HttpException 객체들이 있습니다.
잘 쓰는 응답코드에 대해서는 대체로 이미 만들어져 있는데요, 이 경우에는 404를 내려줄테니,
`throw new NotFoundException("Email does not exist")`
같은 식으로 사용할 수 있겠습니다!

2022-11-27 04:44 UTC, worjs commented on src/user/user.repository.ts
> +    return await this.prisma.user.create({
return await을 사용하신 이유가 있을까요?

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.controller.ts
> +  async register(@Body() createUserDto: CreateUserDto): Promise<User> {
응답 객체로 Entity자체를 바로 내려주는 것 보다는 별도의 응답 객체를 정의해서 내려주는게 더 좋다고 생각합니다.
DB의 스키마는 어떻게보면 요구사항에 따라 언제든 변할 수 있는 세부 사항입니다.

예를들어, 만약 클라이언트 단에서 이 요청을 통해 User객체의 어떤 column을 사용하고 있었는데, 어떠한 이유로 우리가 DB의 스키마를 변경하고 migration을 진행했다고 가정합시다. 이때 클라이언트에서 사용하던 특정 column이 User Entity에서 사라진다면, 이로 인해 예상하지 못한 문제가 서버 배포로 인해 발생할 수 있겠습니다.

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.service.ts
> +  protected async generatedAccessToken(userId: string): Promise<string> {
사소한 거긴 한데, generated보다는 generate가 맞을 것 같아요!

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.controller.ts
> +    @Body() loginUserDto: LoginUserDto,
요청 Body 객체와 응답 Body 객체 모두 nest에서는 Dto라는 이름으로 쓰라고 안내가 되어 있는 편인데요,
그러다보면 어떤건 요청 Body고 어떤건 응답 Body인지 폴더 구조나 네이밍을 통해 구분하기 어렵다고 생각합니다.

그래서 제가 속한 팀에서는 요청 Body의 경우에는 Payload라는 이름을 사용하고, 응답 Body의 경우에는 Dto라는 이름을 사용합니다.
개인적으로는 Payload로 네이밍하는 방식을 제안하지만, 방다른 의견이 있으면 얼마든지 알려주세요!

2022-11-27 04:44 UTC, worjs commented on src/auth/dto/create.user.dto.ts
> +  @IsNotEmpty()
현재 IsNotEmpty 데코레이터는 undefined로 요청을 하면(json에서 아예 항목조차 안만들어서 요청하면) 통과됩니다.

이는 제가 처음에 GlobalValidationPipe를 세팅할때 `skipUndefinedProperties: true`를 추가했기 때문인데요,
undefined로 들어오는 모든 property에 대해서 validation을 생략하는 옵션입니다.
만약 이 옵션을 무시하고 싶다면 IsDefined를 사용하면 됩니다.

관련 case에 대해서는 test.payload.ts 파일에 경우를 나누어서 작성해두었으니 참고하시면 되겠습니다!

추가적으로 굳이 저 옵션을 넣은 이유를 조금 말씀드리면, undefined와 null을 최대한 validation 단계에서 데코레이터만 이용해서 처리하려는 목적이 있었습니다. 저 옵션을 넣지 않으면 IsOptional을 통해서 undefined or null값을 받게되는데, 이 경우 undefined는 허용하지만 null을 허용하지 않는 경우를 validation하기 위해서는 서비스로직 내에서 ?? 연산자 등을 이용해서 추가적인 처리를 진행해야 합니다.

2022-11-27 04:44 UTC, worjs commented on src/auth/dto/token.response.dto.ts
> +  @IsString()
요청 Body의 경우는 controller에 매핑되기 전에 nest에 설정한 global pipe를 통해 데코레이터 설정한대로 validation이 작동합니다.

하지만 이와 같은 응답 Body의 경우에는 직접 validate 함수를 이용해서 validation을 시켜주지 않으면 작동하지 않습니다. 만약 validation을 진행하고자 한다면, 이 객체를 생성하고 validate 함수를 사용하시면 됩니다만, 응답 객체의 경우 서비스 로직을 통과한 상태이기 때문에 별도의 validation이 필요하다고 생각하지 않는 편입니다!

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.service.ts
> +    if (user) return true;
`return !!user;` 같은 문법 어떻게 생각하시나요?

2022-11-27 04:44 UTC, worjs commented on src/auth/auth.service.ts
> +    res.cookie('refresh_token', refreshToken, {
1. 쿠키를 이용해서 refresh_token만 내려주는 방식을 선택하셨군요..! 혹시 이렇게 구현하신 이유가 있을까요?
2. Response 객체는 서비스 로직의 함수가 알 필요가 없다고 생각합니다. controller에서 처리하는게 어떨까요?

2022-11-30 15:11 UTC, worjs approved these changes
추가해주신 부분 잘 확인했고, 대부분 잘 반영해주셨네요!
이전 리뷰에서는 return await 관련한 부분이 따로 반영된 부분이 없어서, 그부분만 알려주시면 될 것 같습니다.

추가된 코멘트들은 대부분 사소한 것들이어서 한번씩 읽어보시고, 마치시는대로 머지하면 되겠습니다!
고생하셨습니다!

2022-11-30 15:11 UTC, worjs commented on prisma/schema.prisma
> +  refreshToken       String?
이렇게 하면 db에 `refreshToken`이라는 camelCase로 반영되었을텐데, db에서는 전부 snake_case로 작성하는게 맞을 것 같아서, 다른 경우처럼 `@map("refresh_token")` 한줄 넣어주시면 될 것 같습니다!

2022-11-30 15:11 UTC, worjs commented on package.json
> +    "bcryptjs": "^2.4.3",
요거 확인해봤을때 bcryptjs가 타입이 안잡히고 있는데, @types/bcryptjs를 devDependency로 설치해주시면 될 것 같습니다.

2022-11-30 15:11 UTC, worjs commented on src/auth/auth.controller.ts
> +  @ApiOkResponse({ type: boolean })
swagger에서 boolean 확인이 안되길래 찾아보니 객체 타입`Boolean`으로 넣어줘야 하는 것 같습니다.

2022-11-30 15:11 UTC, worjs commented on src/auth/auth.controller.ts
> +  @ApiOperation({ summary: 'check whether a name exsits' })
오타가 있네요!

2022-11-30 15:11 UTC, worjs commented on src/auth/auth.service.ts
> +    if (!passwordMatch) throw new Error('Password mismatch');
모든 Error들에 대해 HttpException 관련 클래스로 처리해주시면 감사하겠습니다!

2022-11-30 15:11 UTC, worjs commented on src/auth/auth.service.ts
> +    }
refreshToken을 이용하는 방식을 생각해보면, refreshToken을 생성하면 반드시 DB에 한번 반영을 해야하므로, 지금처럼 별도의 함수로 처리할 필요가 없다고 생각합니다.

하나의 함수로 만들면 다음과 같이 작성할 수 있겠네요.
`const refreshToken = user.refreshToken || (await this.generateRefreshToken(user.id));`

2022-11-30 15:11 UTC, worjs commented on src/auth/auth.service.ts
> +    if (user) throw new Error('Email alreay exists');
error message에 오타가 있네요!

2022-11-30 15:11 UTC, worjs commented on src/auth/payload/create.user.payload.ts
> +  os!: UserOS;
데코레이터중에 `IsEnum`이 있어서 그걸 쓰면 됩니다.
ApiProperty에서도 필드중에 `enum`필드가 있어서, 그걸 쓰면 swagger에서도 enum이 지원됩니다!

2022-11-30 15:11 UTC, worjs commented on src/auth/type/token.response.type.ts
> +export type TokenResponseT = {
여기 끝에 붙은 T는 type이라는 의미의 네이밍인가요? 이런 방식도 좋은 것 같네요

2022-12-03 04:48 UTC, yunz0926 commented on src/user/user.repository.ts
> +    return await this.prisma.user.create({
db 접근 시의 리턴값을 그대로 다시 반환해줄 때 자주 봐온 코드 작성인데, 어떤 부분에서 의문점이 드셨을까용 ?

2022-12-03 04:49 UTC, merged

2022-12-03 07:25 UTC, worjs commented on src/user/user.repository.ts
> +    return await this.prisma.user.create({
이 경우에서는 await을 넣던 안넣던 결과가 같아서, 저는 주로 안넣는 편인데 따로 이렇게 작성하신 이유가 있을까 싶어서 물어봤습니다!