[Feat] Habit 생성하는 API
kugods-HabitTama/dahae-server pull request #20
Opened 2022-12-10 08:17 UTC by rimrim990

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 새로운 해빗을 생성하는 API 를 작성하였습니다.

## Related issue
- #15 

## Additional context
- 사용자가 해빗을 추가할 때, 시간 설정을 초 단위로는 하지 않을 것 같습니다. 따라서 time 전달받을 때 초 정보는 없어도 될 것 같은데, 어떻게 생각하시나요?
- pr 올린 것도 일단은 시간이랑 분 단위로만 체크하도록 구현하였습니다.

2022-12-10 11:42 UTC, worjs requested changes
고생하셨습니다!
거의 대부분의 input들은 잘 막히도록 구성해주셨네요! Additional Context에 작성해주신 의견 다 동의합니다.

리뷰드린 부분은 코드 위치나 사소한 문법들인데, 제 의견이 들어간 부분들이어서 한번 보고 괜찮다 싶으면 반영해주시면 될 것 같습니다.

2022-12-10 11:42 UTC, worjs commented on src/habit/habit.service.ts
> +    createHabitPayload: CreateHabitPayload,
별거 아니긴한데, 이거 이름 payload로 해도 충분할 것 같아요!

2022-12-10 11:42 UTC, worjs commented on src/habit/payload/create.habit.payload.ts
> +  value!: number;
아마 정수만 받기로 했던것으로 기억해서,`@IsInt()` 사용해주면 될 것 같네요!

2022-12-10 11:42 UTC, worjs commented on src/habit/habit.service.ts
> +    };
payload의 어떤 값이 덮어지는거고, 어떤 값이 새로 들어가는지 명확히 하기 위해서 이럴때는 저는 쭉 나열해서 값 할당을 하는 편인데, 어떻게 생각하시나요?

2022-12-10 11:42 UTC, worjs commented on src/habit/habit.service.ts
> +    }
400을 내려줄만한 검증은 최대한 transformer & validator로 해결하는 쪽이 좋을 것 같기는한데, 이거는 조금 귀찮을수도 있어서 시간 없으시면 그냥 넘어가셔도 좋습니다! 나중에 제가 작성해서 공유드릴게요.

2022-12-10 11:42 UTC, worjs commented on src/habit/habit.repository.ts
> +      },
`data: habitData`
이렇게도 가능할 것 같습니다!

2022-12-10 11:42 UTC, worjs commented on src/habit/habit.service.ts
> +    }
이 부분은 payload로 받아온 days라는 배열이나 time값(xx:yy형태의 string) 자체는 의미가 있지만, DB에 저장하거나 ORM을 이용해 작업하기 위해 변환하는 로직입니다. 기본적으로 DB나 ORM은 세부 사항이라고 생각해서, 그쪽에 의존하는 로직들은repository layer에서 처리하는게 좋다고 생각합니다. 그렇게하면 만약 저장하는 방식이나 ORM이 바뀌어도 Service함수는 안건드려도 되니까요.

2022-12-10 11:42 UTC, worjs commented on src/habit/payload/create.habit.payload.ts
> +  @IsOptional()
IsOptional 데코레이터는 null도 통과합니다.
type 정의할때 string | null로 작성해야 혹시나 작업할때 문제가 생기는 부분들 타입체킹이 가능할 것 같습니다!

2022-12-10 11:42 UTC, worjs commented on src/habit/payload/create.habit.payload.ts
> +  endDate?: string;
요기 어떤 format으로 보내면 좋을지 예시 넣어주면 좋을 것 같네요! `example` field를 이용하시면 되겠습니당

2022-12-10 11:42 UTC, worjs commented on src/habit/payload/create.habit.payload.ts
> +    type: Array,
요거는 swagger에서 enum 배열이 안잡혀서 확인해봤는데, 이렇게 수정하면 반영됩니다.
```
@ApiProperty({
    description: '수행 요일',
    isArray: true,
    enum: HabitRecordDay,
  })
```

2022-12-10 11:42 UTC, worjs commented on src/habit/payload/create.habit.payload.ts
> +  days: HabitRecordDay[];
`!` 빠졌습니다!

2022-12-10 11:42 UTC, worjs commented on src/habit/const/habitRecordDay.const.ts
> +} as const;
오 이렇게 쓰는거 좋네요!

2022-12-11 13:35 UTC, rimrim990 commented on src/habit/habit.service.ts
> +    }
오 제가 구현해보겠습니다 !! 감사합니다 ~

2022-12-13 09:24 UTC, yunz0926 commented
@rimrim990 혹시 오늘, 내일 중에 머지 가능하신가요? 생성api 있어야 작업하기 편할 것 같아서 예림님이 만드신 habit 모듈 위에서 작업하려고했는데, 혹시 머지가 늦어질 것 같으면 따로 작업하고 나중에 리베이스하려구여 !

2022-12-13 10:04 UTC, rimrim990 commented
> @rimrim990 혹시 오늘, 내일 중에 머지 가능하신가요? 생성api 있어야 작업하기 편할 것 같아서 예림님이 만드신 habit 모듈 위에서 작업하려고했는데, 혹시 머지가 늦어질 것 같으면 따로 작업하고 나중에 리베이스하려구여 !

넵넵 ! 거의 완료해서 금방 가능할 것 같습니다.

2022-12-13 11:34 UTC, worjs approved these changes
validator 직접 만드셨네요?! 맨날 있는거 가져다 쓸 생각만 했지 직접 만들어본 적은 없는데 좋네요..!
좋은거 배워갑니다~

고생하셨어요!

2022-12-13 11:54 UTC, merged

2022-12-13 16:27 UTC, yunz0926 commented
@rimrim990 예시로 들어주신 '10:10' 형식으로 time 속성 추가해서 api 호출했을 때 500 에러 뜨네용 (time 속성 없을 땐 잘 동작합니당)
아 그리고 payload property에 memo 빠져있습니다 !  

확인 한번 부탁드립니다 🙃

2022-12-14 07:03 UTC, rimrim990 commented
> @rimrim990 예시로 들어주신 '10:10' 형식으로 time 속성 추가해서 api 호출했을 때 500 에러 뜨네용 (time 속성 없을 땐 잘 동작합니당) 아 그리고 payload property에 memo 빠져있습니다 !
> 
> 확인 한번 부탁드립니다 🙃

아 저번 회의에서 memo 는 없애기로 해서 payload 에 추가하지 않았습니다. 
마이그레이션 적용하시면 잘 작동할 것 같습니다. (#14) 적용 후에도 에러나면 알려주세요 !

2022-12-14 12:16 UTC, yunz0926 commented
오호 제가 스키마 변경된 걸 놓치고있었군요 감사합니당 ~🙂