Feat/16
kugods-HabitTama/dahae-server pull request #29
Opened 2022-12-13 18:18 UTC by yunz0926

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [X] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 해빗 리스트 조회, 해빗 기록 조회, 진행도 변경 api 작성

## Related issue
- resolve #16 #18 

## Additional context
- 해빗 기록 조회 api 작성하다보니 해빗 기록 생성 (진행도 변경) 기능이 필요해서 #18 작업을 함께 진행했습니다 
- 해빗 기록 조회 시 진행도 외에도 기록 Id, 달성 여부를 함께 반환해주었습니다

## Checklist
- 달성 여부는 언제 변경되는걸까요? 진행도를 변경할 때 달성 여부도 함께 바꾸는 것인지, 아니면 달성 여부를 바꾸는 시점은 진행도 변경과 별개인지 논의가 필요해보입니다

2022-12-14 16:38 UTC, worjs requested changes
고생하셨습니다! 피드백 조금만 반영해서 주시면 될 것 같네요!

1. 말씀해주신 달성 여부에 관해서 고민해봤는데, 당장은 이 컬림이 필요하지 않은 것 같습니다. value와 progress를 비교해서 value보다 progress가 같거나 크면 달성이라고 판정이 가능한 것 같네요. 다만, 이후에 달성된 record들만 조회한다던가 그것들만 따로 센다던가 하는 케이스가 생기면 그때 다시 고민해보는 쪽으로 가는게 어떨까요?
2. getHabitRecord 관련해서는 저희가 DB 설계하면서 로직 고민할때, 우리는 record만 내려주고 나머지는 프론트가 하는걸로~라고 정했었는데, 사실 

> 입력으로 특정 날짜를 받으면, 해당 일의 Habit들의 정보를 내려주는 API입니다.

라는 역할의 API라면 그정도는 우리가 하는게 좀더 낫지 않을까 해서 이슈에 **진행도가 0이면 0으로 해서 포함시켜서 내려주세요!** 로 말씀을 드렸었습니다. 이전에 이야기한거랑 다른 부분이어서 좀더 명확하게 언급을 했어야 했다고 생각합니다. 이 부분은 로직이 꽤 달라질 것 같아서 바쁘실 것 같으면 이번에는 이대로 가고, 제가 다음에 작업해두겠습니다!

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.controller.ts
> +    @Body() getHabitRecordPayload: GetHabitRecordPayload,
Get 메소드는 Body를 지원하지 않는 경우가 있다고 합니다! path param이나 query string으로 돌리는 쪽이 좋아 보이네요!

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.service.ts
> +    });
가져온 habit을 내보내는 Dto 포맷에 맞춰 변환하는 로직은 해당 Dto에 특화된 로직이여서 여기보다는 Dto class 내에 static 메소드로 정의하는게 어떨까 싶은 의견입니다! user에 dto폴더 보시면 저는 보통 static of 이런 형태로 주로 사용하는 편입니다.

추가로, 실제 요청을 보내보면 userId, createdAt, updatedAt, isActive 같은 값들도 내려오는데, 이를 방지하려면 하나하나 꺼내서 값을 복사하는 과정이 필요해 보입니다.

2022-12-14 16:38 UTC, worjs commented on src/utils/date.ts
> +};
이 함수들 리턴타입 넣어주세요~

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.repository.ts
> +        userId,
유저 조회할때 저희가 `deletedAt`(soft delete)를 넣었기 때문에, `deletedAt: null` 조건이 기본으로 들어가야 할 것 같습니다!

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.repository.ts
> +  getHabits(userId: string): Promise<Habit[]> {
await 문을 당장은 쓰지 않더라도 다른 로직이 함수에 추가되면서 사용될 수 있기도 하고, promise를 리턴하는 함수라면 async 키워드를 달아주는게 가독성 측면에서도 좋을 것 같습니다!

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.repository.ts
> +  async changeProgress(payload: ChangeProgressPayload): Promise<HabitRecord> {
아래 두 가지를 참고하면 좀 더 간결하게 개선이 가능할 것 같습니다!

1. 스키마 설계할때 habitId, date로 unique 제약을 걸어두었는데요, 조회할때 habitRecord.findUnique하고, where절에서 habitId_date라는 prop으로 이 조건을 사용할 수 있습니다.
2. prisma에서는 upsert라는 함수를 지원하고 있는데, unique 조건으로 검색해서 나온 항이 존재하면 update, 존재하지 않으면 create하는 함수입니다.

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.service.ts
> +  async changeProgress(payload: ChangeProgressPayload): Promise<void> {
요청할때 habitId와 date를 받아서 요청하게 되는데, 만약에 habit은 수, 금에 수행하는 habit인데 다른 요일을 date로 올려주면 데이터의 정합성이 깨져버립니다. 해당 date가 등록된 habit의 요일에 대해 적절한지 검증하는 로직이 선행되어야 할 것 같습니다!

2022-12-14 16:38 UTC, worjs commented on src/habit/dto/get.habit.record.dto.ts
> +  @ApiProperty({ type: Number, description: '습관 기록 Id' })
recordId를 클라에 내려줄 이유가 진행도 변경할때 id로 요청하는 정도인데, 우리가 설계한 구조에서는 id가 아니라 habitId & date로 요청을 보내기로 하였으니 따로 내려주지 않아도 괜찮을 것 같습니다!

2022-12-14 16:38 UTC, worjs commented on src/habit/dto/get.habit.dto.ts
> +  endDate!: Date;
`@IsOptional`은 validator여서 이 상황에서는 적용이 안되고, swagger에 optional value임을 보여주려면 `@ApiPropertyOptional`을 사용하면 되겠습니다~

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.controller.ts
> +  ): Promise<GetHabitDto[]> {
1. Dto는 배열로 내려주기보다는 별도의 감싸는 Dto를 만들어서 `{ habits: GetHabitDto[] } : GetHabitListDto`를 내려주는게 더 낫다고 생각하는데요, 그래야 도중에 다른 값을 추가하는 식으로 Dto를 변경하더라도, 하위호환성을 유지할 수 있기 때문입니다. 

2. 응답 포맷 swagger는 `@ApiOkResponse`(200), `@ApiCreatedResponse`(201) 등을 사용하면 됩니다!
ex) `@ApiCreatedResponse({type: GetHabitListDto})`

2022-12-14 16:38 UTC, worjs commented on src/habit/habit.controller.ts
> +  @Patch('/')
이 함수의 경우에는 자원이 없는경우는 생성되기도 하고, 요청만으로 모든 자원의 상태를 나타낼 수 있으므로 Patch보다는 Put이 적합하다고 생각합니다.
관련해서 좋은 글이 있어서 소개합니다~
https://tecoble.techcourse.co.kr/post/2020-08-17-put-vs-patch/

2022-12-17 12:42 UTC, worjs commented
@yunz0926 혹시 수정 끝나셨나요?

2022-12-17 13:03 UTC, yunz0926 commented
@worjs 진행도 0인 습관 포함해서 반환해주는 로직을 아직 수정 못했는데 지금 밖에 나와있어서 새벽 내로 작업해서 머지해놓겠습니다 !

2022-12-17 15:01 UTC, merged