[Feat] Habit 수정/삭제 API
kugods-HabitTama/dahae-server pull request #32
Opened 2022-12-17 16:39 UTC by yunz0926

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [X] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- habit 수정 / 삭제

## Related issue
- resolve #17

2022-12-17 17:23 UTC, worjs commented
rebase해서 푸쉬해두었습니다!

2022-12-18 04:18 UTC, worjs requested changes
고생하셨습니다! 자세한 부분은 코멘트 확인해주세요~

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.controller.ts
> +  async deleteHabit(@Param('id') id): Promise<void> {
@Param 데코레이터로 path param값을 가져올때, url 자체는 string이기 때문에 런타임에서 id가 int가 맞는지 보장되지 않습니다. Int가 맞는지 validation을 수행해야하는데, nest docs에서 pipe 관련부분을 보시면 될 것 같네요!

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.controller.ts
> +  @Patch('/')
특정 id의 habit을 수정하는거니까 id를 path param으로 받아도 괜찮지 않을까요?

2022-12-18 04:18 UTC, worjs commented on src/habit/payload/update.habit.payload.ts
> +  title!: string;
update 쿼리를 실행할때 data에 값을 null로 주는 경우와 undefined로 주는 경우가 있는데, 전자는 쿼리에서 값을 null로 넣으려 할거고, 후자는 업데이트 하지 않겠다는 의미입니다. 
title에 대해 생각해보면, db에서는 nullable하지 않기 때문에 null로 값이 들어오는 경우는 막아야하고, 업데이트 안할 수는 있기 때문에 undefined는 허용해야합니다.

global validation pipe를 main.ts에 세팅해둔 상태인데, `skipUndefinedProperties : true`옵션을 켜둔 상태이기 때문에, 기본적으로 undefined인 경우는 나머지 validation을 무시하고 통과합니다. `@IsOptional`은 null & undefined 인 경우에 나머지 validation을 무시하고 통과합니다.

즉 이 경우에는, 아래와 같이 작성하는 것이 맞겠습니다. `@IsNotEmpty`를 넣으면 추가로 ""와 같은 empty string을 막을 수 있습니다.
```
  @IsNotEmpty()
  @IsString()
  @ApiPropertyOptional({
    type: String,
    description: '제목',
  })
  title?: string;
```

같은 관점에서 나머지 input들도 한번씩 점검해 주시면 되겠습니다!

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.repository.ts
> +      }
delete 이후에 BadRequestException이 발생되면 삭제만 수행된 채로 끝나게 됩니다..! 데이터만 먼저 가져온 다음에 검증이 끝나고 수행하는게 좋겠네요!

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.repository.ts
> +          value: value === undefined ? habit.value : value,
value만 이렇게 작성된 이유가 있나요?

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.repository.ts
> +      }
그러고 보니 이 검증이 아래에도 있어야겠네요!

2022-12-18 04:18 UTC, worjs commented on src/habit/habit.repository.ts
> +  async update(userId: string, payload: UpdateHabitPayload): Promise<Habit> {
공통되는 검증 로직은 위쪽에서 모아서 처리하고, 나머지 input에 따른 분기 부분은 별도의 함수로 분리하면 가독성이 올라갈 것 같기도 합니다!

2022-12-18 14:44 UTC, yunz0926 commented on src/habit/habit.repository.ts
> +          value: value === undefined ? habit.value : value,
흠 nullable로 착각한 것 같습니다

2022-12-18 14:45 UTC, merged