[Feat] Prisma Init & prisma schema 작성
kugods-HabitTama/dahae-server pull request #8
Opened 2022-11-23 11:57 UTC by rimrim990

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 저번 회의 결과를 바탕으로 스키마 작성 후, migration 진행했습니다.
- 기존의 routine_setting 을 habbit 으로, routine 을 habbit_record 로 수정하였습니다.
- 각 habbit 마다 시간을 설정하기 위한 time 필드를 추가하였습니다.

## Related issue
- #3 

## Additional context
~~실행 방법~~
~~1. db 와 prisma 연결하기~~
-  루트 디렉터리에 `.env` 파일 추가
- `.env` 파일 내부에 `DATABASE_URL` 필드 추가
- https://www.prisma.io/docs/reference/database-reference/connection-urls

~~2. db 에 migration 에 적용하기~~
- `npx prisma migrate dev`

## Checklist
- habbit 시간 설정을 위한 time 필드를 일단 int 로 설정했는데 적절한지 확인 부탁드립니다.

2022-11-23 15:51 UTC, worjs requested changes
와 거의 고쳐야할게 없네요! 고생하셨습니다~!

1. prisma format 치면 schema 문법 잡아주고 예쁘게 고쳐주니까 한번 실행해서 올려주시면 될 것 같습니다.

2. 그리고 환경변수 관련해서는,
script를 만들어둔 상태인데, local, dev, prod 각각 .local.env,    .dev.env,    .prod.env 파일 만들어두고 해당 스크립트를 실행하면 각 환경으로 돌릴 수 있습니다. 환경변수는 슬랙에 공유해드릴게요!
3. 2번 방식으로 했을때 런타임에서 환경변수가 주입이 잘 안되는 문제가 있어서 올릴 예정입니다. 그거 rebase해서 다시 올려주시면 되겠습니다..!

2022-11-23 15:51 UTC, worjs commented on prisma/schema.prisma
> +enum Role {
1. enum들은 여러 맥락(table)에서 사용되는 것들이 아니라면 UserRole, HabitUnit 등과 같이 맥락을 붙여서 네이밍하는 것이 더 좋겠다 생각이 드는데 어떠신가요?
2. enum에서도 @@map이 지원되니까 가는김에 전부 snake_case로 통일하면 좋겠습니다.

2022-11-24 16:50 UTC, rimrim990 commented on prisma/schema.prisma
> +enum Role {
넵 동의합니다. 수정하였습니다 ~

2022-11-25 01:49 UTC, worjs commented
고생하셨습니다!

2022-11-25 01:49 UTC, worjs approved these changes
고생하셨습니다!

2022-11-25 05:48 UTC, merged